<?php

namespace Database\Seeders;

use App\Models\RequestCreditHelp;
use Illuminate\Database\Seeder;

class RequestCreditHelpTableSeeder extends Seeder
{
    public function run()
    {
        $requestCreditHelp = [
            [
                'id' => 1,
                'type' => 'tenors',
                'attribute' => '1',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 2,
                'type' => 'tenors',
                'attribute' => '2',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 3,
                'type' => 'tenors',
                'attribute' => '3',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 4,
                'type' => 'tenors',
                'attribute' => '4',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 5,
                'type' => 'tenors',
                'attribute' => '5',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 6,
                'type' => 'placeholders',
                'attribute' => 'Other',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 7,
                'type' => 'brands',
                'attribute' => 'Toyota',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 8,
                'type' => 'brands',
                'attribute' => 'Daihatsu',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 9,
                'type' => 'brands',
                'attribute' => 'Honda',
                'attribute_2' => '',
                'attribute_3' => '',
            ],            [
                'id' => 10,
                'type' => 'brands',
                'attribute' => 'Mitsubishi Motors',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 11,
                'type' => 'brands',
                'attribute' => 'Hyundai',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 12,
                'type' => 'brands',
                'attribute' => 'Mitsubishi FUSO',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 13,
                'type' => 'brands',
                'attribute' => 'Isuzu',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 14,
                'type' => 'brands',
                'attribute' => 'Hino',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 15,
                'type' => 'brands',
                'attribute' => 'Wuling',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 16,
                'type' => 'brands',
                'attribute' => 'Mazda',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 17,
                'type' => 'brands',
                'attribute' => 'Chery',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 18,
                'type' => 'brands',
                'attribute' => 'BMW',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 19,
                'type' => 'brands',
                'attribute' => 'Mercedes-Benz',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 20,
                'type' => 'brands',
                'attribute' => 'Lexus',
                'attribute_2' => '',
                'attribute_3' => '',
            ],            [
                'id' => 21,
                'type' => 'brands',
                'attribute' => 'UD Trucks',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 22,
                'type' => 'brands',
                'attribute' => 'Nissan',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 23,
                'type' => 'brands',
                'attribute' => 'KIA',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 24,
                'type' => 'brands',
                'attribute' => 'DFSK',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 25,
                'type' => 'brands',
                'attribute' => 'Morris Garage',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 26,
                'type' => 'brands',
                'attribute' => 'Mini',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 27,
                'type' => 'brands',
                'attribute' => 'Subaru',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 28,
                'type' => 'brands',
                'attribute' => 'FAW',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 29,
                'type' => 'brands',
                'attribute' => 'JEEP',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 30,
                'type' => 'brands',
                'attribute' => 'VolksWagen',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 31,
                'type' => 'brands',
                'attribute' => 'Peugeot',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 32,
                'type' => 'brands',
                'attribute' => 'Audi',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 33,
                'type' => 'brands',
                'attribute' => 'TATA',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 34,
                'type' => 'brands',
                'attribute' => 'Seres',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 35,
                'type' => 'brands',
                'attribute' => 'Citroen',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 36,
                'type' => 'brands',
                'attribute' => 'Datsun',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 37,
                'type' => 'brands',
                'attribute' => 'Scania',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 38,
                'type' => 'brands',
                'attribute' => 'Infiniti',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 39,
                'type' => 'brands',
                'attribute' => 'Hongyan',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 40,
                'type' => 'dealers',
                'attribute' => '99 Autocars',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 41,
                'type' => 'dealers',
                'attribute' => 'AMS BSD',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 42,
                'type' => 'dealers',
                'attribute' => 'AMS Tangerang City',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 43,
                'type' => 'dealers',
                'attribute' => 'Andalan Bekasi Timur',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 44,
                'type' => 'dealers',
                'attribute' => 'Andalan Sawah Besar',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 45,
                'type' => 'dealers',
                'attribute' => 'Anugerah Mandiri',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 46,
                'type' => 'dealers',
                'attribute' => 'Apple Motor',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 47,
                'type' => 'dealers',
                'attribute' => 'Arfa Motor',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 48,
                'type' => 'dealers',
                'attribute' => 'Arjuna Taman Anggrek',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 49,
                'type' => 'dealers',
                'attribute' => 'Artha Mobilindo',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 50,
                'type' => 'dealers',
                'attribute' => 'Auto Cipta Karya BSD',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 51,
                'type' => 'dealers',
                'attribute' => 'Bagus Jaya Motor',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 52,
                'type' => 'dealers',
                'attribute' => 'BEM Auto',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 53,
                'type' => 'dealers',
                'attribute' => 'Berkah Jaya Mobilindo',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 54,
                'type' => 'dealers',
                'attribute' => 'Berkah Motor',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 55,
                'type' => 'dealers',
                'attribute' => 'Blessing Auto Cars',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 56,
                'type' => 'dealers',
                'attribute' => 'Bra Cikupa',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 57,
                'type' => 'dealers',
                'attribute' => 'Bumen Redja Abadi',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 58,
                'type' => 'dealers',
                'attribute' => 'ByPASSindo',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 59,
                'type' => 'dealers',
                'attribute' => 'Chery Bekasi',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 60,
                'type' => 'dealers',
                'attribute' => 'Chery Depok',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 61,
                'type' => 'dealers',
                'attribute' => 'Chery Pondok Indah',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 62,
                'type' => 'dealers',
                'attribute' => 'Dai As Sayaarah',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 63,
                'type' => 'dealers',
                'attribute' => 'Dasta Motor 2',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 64,
                'type' => 'dealers',
                'attribute' => 'Dayaguna Motor Indonesia',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 65,
                'type' => 'dealers',
                'attribute' => 'Devo Auto Mobilindo',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 66,
                'type' => 'dealers',
                'attribute' => 'Dexi Auto',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 67,
                'type' => 'dealers',
                'attribute' => 'DJM Mobilindo Depok',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 68,
                'type' => 'dealers',
                'attribute' => 'Felix Motor Mobilindo',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 69,
                'type' => 'dealers',
                'attribute' => 'Gowa Hyundai Karawaci',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 70,
                'type' => 'dealers',
                'attribute' => 'Gowa Hyundai Lotte',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 71,
                'type' => 'dealers',
                'attribute' => 'Gowa Narogong',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 72,
                'type' => 'dealers',
                'attribute' => 'Gracio Auto',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 73,
                'type' => 'dealers',
                'attribute' => 'Hikmah Motor',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 74,
                'type' => 'dealers',
                'attribute' => 'HMI BSD',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 75,
                'type' => 'dealers',
                'attribute' => 'HMI Kelapa Gading',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 76,
                'type' => 'dealers',
                'attribute' => 'HMI Sunter',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 77,
                'type' => 'dealers',
                'attribute' => 'Honda Depok',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 78,
                'type' => 'dealers',
                'attribute' => 'Honda Permata Hijau',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 79,
                'type' => 'dealers',
                'attribute' => 'Hyundai Andalan Bekasi',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 80,
                'type' => 'dealers',
                'attribute' => 'Hyundai Andalan Bogor',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 81,
                'type' => 'dealers',
                'attribute' => 'Hyundai Andalan Mampang',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 82,
                'type' => 'dealers',
                'attribute' => 'Hyundai Andalan SMB',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 83,
                'type' => 'dealers',
                'attribute' => 'Hyundai Arista Depok',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 84,
                'type' => 'dealers',
                'attribute' => 'Hyundai Arista Pluit',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 85,
                'type' => 'dealers',
                'attribute' => 'Hyundai Arjuna AEON Cakung',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 86,
                'type' => 'dealers',
                'attribute' => 'Hyundai Bintaro',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 87,
                'type' => 'dealers',
                'attribute' => 'Hyundai Cibubur',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 88,
                'type' => 'dealers',
                'attribute' => 'Hyundai Ciputat',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 89,
                'type' => 'dealers',
                'attribute' => 'Hyundai Fatmawati',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 90,
                'type' => 'dealers',
                'attribute' => 'Hyundai HMI Cilandak',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 91,
                'type' => 'dealers',
                'attribute' => 'Hyundai HMI Kalimalang',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 92,
                'type' => 'dealers',
                'attribute' => 'Hyundai HMI Simprug',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 93,
                'type' => 'dealers',
                'attribute' => 'Hyundai HMI Pancoran',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 94,
                'type' => 'dealers',
                'attribute' => 'Hyundai PIM',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 95,
                'type' => 'dealers',
                'attribute' => 'Hyundai Pondok Gede',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 96,
                'type' => 'dealers',
                'attribute' => 'Hyundai Sinar Inti Cimanggis',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 97,
                'type' => 'dealers',
                'attribute' => 'Hyundai Sinar Inti Puri Mall',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 98,
                'type' => 'dealers',
                'attribute' => 'Hyundai Sun Panjaitan',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 99,
                'type' => 'dealers',
                'attribute' => 'Hyundai Tajur',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 100,
                'type' => 'dealers',
                'attribute' => 'Indo Truck Utama',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 101,
                'type' => 'dealers',
                'attribute' => 'Jaya Saputra Motor',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 102,
                'type' => 'dealers',
                'attribute' => 'Johan Motor',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 103,
                'type' => 'dealers',
                'attribute' => 'Kanindo Medan',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 104,
                'type' => 'dealers',
                'attribute' => 'Kenzo Auto Mobilindo',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 105,
                'type' => 'dealers',
                'attribute' => 'KIA MT Haryono',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 106,
                'type' => 'dealers',
                'attribute' => 'Koi Mobilindo',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 107,
                'type' => 'dealers',
                'attribute' => 'Maju Motor Cibinong',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 108,
                'type' => 'dealers',
                'attribute' => 'Maya Graha Indah',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 109,
                'type' => 'dealers',
                'attribute' => 'MBK Auto',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 110,
                'type' => 'dealers',
                'attribute' => 'Mitsu Bra Tebet',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 111,
                'type' => 'dealers',
                'attribute' => 'Mitsubishi Bekasi',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 112,
                'type' => 'dealers',
                'attribute' => 'Mitsubishi Bogor Yasmin',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 113,
                'type' => 'dealers',
                'attribute' => 'Mitsu Bra BSD',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 114,
                'type' => 'dealers',
                'attribute' => 'Mitsubishi Cempaka',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 115,
                'type' => 'dealers',
                'attribute' => 'Mitsubishi Dipo Puri Indah',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 116,
                'type' => 'dealers',
                'attribute' => 'Mitsubishi Fatmawati',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 117,
                'type' => 'dealers',
                'attribute' => 'Mitsubishi Sun Star Prima Cibubur',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 118,
                'type' => 'dealers',
                'attribute' => 'Nauli Motor',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 119,
                'type' => 'dealers',
                'attribute' => 'Net Auto',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 120,
                'type' => 'dealers',
                'attribute' => 'Osaka Motor',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 121,
                'type' => 'dealers',
                'attribute' => 'Oto.com',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 122,
                'type' => 'dealers',
                'attribute' => 'Philips Motor',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 123,
                'type' => 'dealers',
                'attribute' => 'Plaza Toyota',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 124,
                'type' => 'dealers',
                'attribute' => 'Plaza Toyota Citeureup',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 125,
                'type' => 'dealers',
                'attribute' => 'Plaza Toyota Kyai Tapa',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 126,
                'type' => 'dealers',
                'attribute' => 'Plaza Toyota Pemuda',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 127,
                'type' => 'dealers',
                'attribute' => 'Plutos Auto',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 128,
                'type' => 'dealers',
                'attribute' => 'Pratama Mandiri',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 129,
                'type' => 'dealers',
                'attribute' => 'PT Kobexindo Tracktors, TBK',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 130,
                'type' => 'dealers',
                'attribute' => 'PT Sentra Multi Karya',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 131,
                'type' => 'dealers',
                'attribute' => 'PT United Equipment Indonesia',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 132,
                'type' => 'dealers',
                'attribute' => 'PT Hyundai Construction',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 133,
                'type' => 'dealers',
                'attribute' => 'Radja Mobilindo',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 134,
                'type' => 'dealers',
                'attribute' => 'Raja BMS',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 135,
                'type' => 'dealers',
                'attribute' => 'Rassya Motor',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 136,
                'type' => 'dealers',
                'attribute' => 'Refinancing',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 137,
                'type' => 'dealers',
                'attribute' => 'Salabenda Auto',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 138,
                'type' => 'dealers',
                'attribute' => 'Sandjaya',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 139,
                'type' => 'dealers',
                'attribute' => 'Siloam Mobilindo',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 140,
                'type' => 'dealers',
                'attribute' => 'Sinar Inti Hyundai AEON Sentul',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 141,
                'type' => 'dealers',
                'attribute' => 'Sinar Inti Hyundai Tanjung Barat',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 142,
                'type' => 'dealers',
                'attribute' => 'Sun Hyundai Joglo',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 143,
                'type' => 'dealers',
                'attribute' => 'Sun Motor Ahmad Yani',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 144,
                'type' => 'dealers',
                'attribute' => 'Sun Motor Juanda',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 145,
                'type' => 'dealers',
                'attribute' => 'Sun89 Mobilindo',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 146,
                'type' => 'dealers',
                'attribute' => 'Surya Timur Jaya',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 147,
                'type' => 'dealers',
                'attribute' => 'Take Over',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 148,
                'type' => 'dealers',
                'attribute' => 'Tunas Toyota Balaraja',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 149,
                'type' => 'dealers',
                'attribute' => 'Wuling Maju Motor Pondok Gede',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 150,
                'type' => 'insurances',
                'attribute' => 'Comprehensive',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 151,
                'type' => 'insurances',
                'attribute' => 'TLO',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 152,
                'type' => 'insurances',
                'attribute' => 'Kombinasi',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 153,
                'type' => 'products',
                'attribute' => 'New Passanger Car',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 154,
                'type' => 'products',
                'attribute' => 'New Commercial Vehicle',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 155,
                'type' => 'products',
                'attribute' => 'Used Passanger Car',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 156,
                'type' => 'products',
                'attribute' => 'Used Passanger Vehicle',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 157,
                'type' => 'products',
                'attribute' => 'Refinancing',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 158,
                'type' => 'Heavy Equipment',
                'attribute' => 'Kombinasi',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 159,
                'type' => 'products',
                'attribute' => 'Motorcycle',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
            [
                'id' => 160,
                'type' => 'products',
                'attribute' => 'Factoring',
                'attribute_2' => '',
                'attribute_3' => '',
            ],
        ];

        RequestCreditHelp::insert($requestCreditHelp);
    }
}
