<?php
// Variables
return [
  "creatorName" => "Credit Checking",
  "creatorUrl" => "",
  "templateName" => "Credit Checking",
  "templateSuffix" => "Website",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "Start your development with a Dashboard for Bootstrap 5",
  "templateKeyword" => "dashboard, bootstrap 5 dashboard, bootstrap 5 design, bootstrap 5",
  "licenseUrl" => "",
  "livePreview" => "",
  "productPage" => "",
  "support" => "",
  "moreThemes" => "",
  "documentation" => "",
  "generator" => "",
  "changelog" => "",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => "",
  "date_format" => "Y-m-d",
  "time_format" => "H:i:s",
  "primary_language" => "en",
  "available_languages" => [
    "en" => 'English',
  ],
  "registration_default_role" => "2",
];
